version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - phpstan
      - phpunit

  phpstan:
    image: php:8.2-cli
    container_name: phpstan
    volumes:
      - .:/var/www/html
    entrypoint: ["vendor/bin/phpstan", "analyse", "--level=max", "src"]

  phpunit:
    image: php:8.2-cli
    container_name: phpunit
    volumes:
      - .:/var/www/html
    entrypoint: ["vendor/bin/phpunit"]